### ISSUE TITLE
Many questions for the projet Guild

### ISSUE THREAD

**Issue by DDril** [danneu/guild#171]
Hello,
I discovered your project yesterday and I have some questions, because it concerns me greatly! Is this the type of forum used on https://www.roleplayerguild.com/?
Also, I am in the interrogation of knowing if it is possible to translate it? I saw that it was HTML and that the language keys were hard, so it would force to change to each of the updates.
If necessary, I can propose to translate it into the French language if you plan that it is not only in English :)
Hoping to hear some news from you.
Cordially.

**Comment by danneu** [comment]
@DDril Hey!

Yes, this is the software that runs that website. However, the software is unfortunately so tied to that website that it cannot be reused.

Thanks for the offer. It would be cool to have different languages available, but I don't think I have enough French-speaking users to make the effort worthwhile, so I will have to decline.

**Comment by DDril** [comment]
@danneu Hey !
What a shame! But thank you for your answer and hope that your script will evolve in the good.

Thanks again :)
